### ISSUE TITLE
Munibot_es failing since 26th March

### ISSUE THREAD

**Issue by amercader** [amercader/munibot#3]
`GetMap` requests fail with:

```
2021-04-02 23:22:17,447 INFO  [munibot.munibot] Start: create image for feature 34070505107 on profile es
/home/adria/dev/pyenvs/munis/src/munibot_es/munibot_es/profiles/es.py:53: RuntimeWarning: Sequential read of iterator was interrupted. Resetting iterator. This can negatively impact the performance.
  geometry = [f["geometry"] for f in src][0]
2021-04-02 23:22:17,861 DEBUG [munibot.image] Received boundaries from profile ((40.654864, -5.137099, 40.704987, -5.070794))
Traceback (most recent call last):
  File "/home/adria/dev/pyenvs/munis/bin/munibot", line 11, in <module>
    load_entry_point('munibot', 'console_scripts', 'munibot')()
  File "/home/adria/dev/pyenvs/munis/src/munibot/munibot/munibot.py", line 97, in main
    create_image(profile, id_, output)
  File "/home/adria/dev/pyenvs/munis/src/munibot/munibot/image.py", line 109, in create_image
    base_image = profile.get_base_image(extent)
  File "/home/adria/dev/pyenvs/munis/src/munibot_es/munibot_es/profiles/es.py", line 70, in get_base_image
    return self.get_wms_image(**wms_options)
  File "/home/adria/dev/pyenvs/munis/src/munibot/munibot/profiles/base.py", line 168, in get_wms_image
    wms = WebMapService(url, version=version, headers=headers)
  File "/home/adria/dev/pyenvs/munis/lib/python3.8/site-packages/OWSLib-0.20.0-py3.8.egg/owslib/wms.py", line 54, in WebMapService
    return wms130.WebMapService_1_3_0(
  File "/home/adria/dev/pyenvs/munis/lib/python3.8/site-packages/OWSLib-0.20.0-py3.8.egg/owslib/map/wms130.py", line 87, in __init__
    self._buildMetadata(parse_remote_metadata)
  File "/home/adria/dev/pyenvs/munis/lib/python3.8/site-packages/OWSLib-0.20.0-py3.8.egg/owslib/map/wms130.py", line 106, in _buildMetadata
    self.operations.append(OperationMetadata(elem))
  File "/home/adria/dev/pyenvs/munis/lib/python3.8/site-packages/OWSLib-0.20.0-py3.8.egg/owslib/map/wms130.py", line 728, in __init__
    url = verb.find(nspath('OnlineResource', WMS_NAMESPACE)).attrib['{http://www.w3.org/1999/xlink}href']
KeyError: '{http://www.w3.org/1999/xlink}href'
```

Cat profile works fine

**Comment by amercader** [comment]
The PNOA WMS GetCapabilities response has an incorrect `xmlns:xlink` attribute that makes OWSLib choke (`"https://www.w3.org/1999/xlink"` vs `"http://www.w3.org/1999/xlink"):

```xml

			<GetFeatureInfo>
				<Format>text/html</Format>
				<Format>text/plain</Format>
				<Format>application/vnd.ogc.gml</Format>
				<Format>application/json</Format>
				<DCPType>
					<HTTP>
						<Get>
							<OnlineResource xmlns:xlink="https://www.w3.org/1999/xlink" xlink:type="simple" xlink:href="http://www.ign.es/wms-inspire/pnoa-ma?SERVICE=WMS&amp;"/>
						</Get>
						<Post>
							<OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:type="simple" xlink:href="http://www.ign.es/wms-inspire/pnoa-ma?SERVICE=WMS&amp;"/>
						</Post>
					</HTTP>
				</DCPType>
			</GetFeatureInfo>
```

We'll patch OWSLib to accept the `https` version for now.

**Comment by amercader** [comment]
Using this patch for now, bot is working again:

```diff
diff --git a/owslib/map/wms130.py b/owslib/map/wms130.py
index ab3f97b..0217ec6 100644
--- a/owslib/map/wms130.py
+++ b/owslib/map/wms130.py
@@ -731,7 +731,10 @@ class OperationMetadata(object):
         self.formatOptions = [f.text for f in elem.findall(nspath('Format', WMS_NAMESPACE))]
         self.methods = []
         for verb in elem.findall(nspath('DCPType/HTTP/*', WMS_NAMESPACE)):
-            url = verb.find(nspath('OnlineResource', WMS_NAMESPACE)).attrib['{http://www.w3.org/1999/xlink}href']
+            try:
+                url = verb.find(nspath('OnlineResource', WMS_NAMESPACE)).attrib['{http://www.w3.org/1999/xlink}href']
+            except KeyError:
+                url = verb.find(nspath('OnlineResource', WMS_NAMESPACE)).attrib['{https://www.w3.org/1999/xlink}href']
             self.methods.append({'type': xmltag_split(verb.tag), 'url': url})

```
